{% set name = "gunicorn" %}
{% set version = "19.8.0" %}
{% set sha256 = "eb8d8924b117a609fae9f8cd85df0cad3535dd613fdbcdbba3ee88d5459f1d4f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version}}.tar.gz
  url: https://pypi.io/packages/source/g/gunicorn/gunicorn-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: True  # [win]
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  preserve_egg_dir: True
  entry_points:
    - gunicorn=gunicorn.app.wsgiapp:run
    - gunicorn_paster=gunicorn.app.pasterapp:run

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools

test:
  imports:
    - gunicorn
    - gunicorn.app
    - gunicorn.http
    - gunicorn.instrument
    - gunicorn.workers
  commands:
    - gunicorn --help
    - gunicorn_paster --help
  requires:
    - paste
    - pastedeploy

about:
  home: http://gunicorn.org
  license: MIT
  license_file: LICENSE
  summary: 'WSGI HTTP Server for UNIX'

extra:
  recipe-maintainers:
    - kwilcox
    - daf
    - jakirkham
    - sodre
