{% set version = "20.0.4" %}

package:
  name: gunicorn
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/gunicorn/gunicorn-{{ version }}.tar.gz
  sha256: 1904bb2b8a43658807108d59c3f3d56c2b6121a701161de0ddf9ad140073c626

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  preserve_egg_dir: True
  skip: True  # [py27]
  entry_points:
    - gunicorn=gunicorn.app.wsgiapp:run

requirements:
  build:
    - python
    - pip
  run:
    - python
    - setuptools

test:
  imports:
    - gunicorn
    - gunicorn.app
    - gunicorn.http
    - gunicorn.instrument
    - gunicorn.workers
  commands:
    - gunicorn --help
  requires:
    - paste
    - pastedeploy

about:
  home: http://gunicorn.org
  license: MIT
  license_file: LICENSE
  summary: 'WSGI HTTP Server for UNIX'

extra:
  recipe-maintainers:
    - kwilcox
    - daf
    - jakirkham
    - sodre
